name: resistors

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install Angular-cli globally
        run: npm install -g @angular/cli@9
      
      - name: Install dependencies
        run: npm install
      
      - name: Unit-test the app
        run: ng test
        
      - name: Install Protractor
        run: npm install protractor --save-dev
        
      - name: Update Webdriver
        run: ./node_modules/protractor/bin/webdriver-manager update
        
      - name: E2E test the app
        run: ng e2e
        
      - name: Build Docker
        run: docker build -t project4 .
        
      - name: Run Docker 
        run: docker run -d -p 4200:4200 project4
